### ISSUE TITLE
USER STORY 1 - Poll

### ISSUE THREAD

**Issue by bdolan55** [bdolan55/My-First-Agile-Project#3]
In order to **interact with other runners** as a **member of the love running website**, I can **vote on a poll and see what is the most popular choice on a topic or view**

**Comment by bdolan55** [comment]
In order to interact with other runners as a member of the love running website, I can vote on a poll and see what is the most popular choice on a topic or view.

### Acceptance Criteria:
* Give the option to members of the love running site to ask site admin to create a Poll
* Give the option to vote on the Poll
* When Vote is cast by the user they should be able to see the current ranking on the poll

### Tasks
- [ ] Create a contact Admin Tab that has a subject dropdown box with different subjects to tell site admin what this mail is about. The dropdown should have subjects related to site ie. poll, user reporting, technical difficulties, general etc etc.
- [ ] Create a section of the site named "Views & Qs". Develop and style a interactive poll using html, CSS and JavaScript.
- [ ] Using JavaScript, Create a feature that displays the poll results after vote has been cast by the user.


### Story Point Estimation 

| Acceptance Criteria  | Story Point Est | Tasks  |
| :---        |    :----:   |          ---: |
| Give the option to members of the love running site to ask site admin to create a Poll      |  2   |  Create New Page a comment box with dropdown list and send button to send to admin email |
|  Create a section of the site named "Views & Qs". Develop and style a interactive poll using html, CSS and JavaScript.  | 4        |  Create "Views & Qs" Page and develop a 4-8 way bar type chart poll. Keep color pallete similar to site colours |
|  Using JavaScript, Create a feature that displays the poll results after vote has been cast by the user.  | 2       |  Create a function to show the Poll results so far when a user casts there vote. Keep hidden until vote is made. |
