### ISSUE TITLE
USER STORY 2 - Poll

### ISSUE THREAD

**Issue by bdolan55** [bdolan55/My-First-Agile-Project#4]
In order to **verbally voice my opinion on a topic** as a **site member**, I can **leave a comment below the topic poll**

**Comment by bdolan55** [comment]
In order to verbally voice my opinion on a topic as a site member, I can leave a comment below the topic poll

### Acceptance Criteria:
* When a vote is cast a comment box should become available to write a comment below poll
* A reply button could be available for another user to comment back on reply and create a thread
* A Thumbs up or Thumbs down button available on comments to show support or reject comments


### Tasks
- [ ] Develop a comments section below the poll that appears when user casts there vote.
- [ ] Create a reply button on each comment to allow users to interact with each others comments/views.
- [ ] within each user comment develop a vote up vote down button to see a positive/negative response from other users on comments.


| Acceptance Criteria  | Story Point Est | Tasks  |
| :---        |    :----:   |          ---: |
|Develop a comments section below the poll that appears when user casts there vote. |  4   |  Create a comments section below Poll. Create functionality on textboxes using JavaScript |
|  Create a reply button on each comment to allow users to interact with each others comments/views.  | 2        |  Reply button to be styled with CSS and functionality created with JavaScript  |
|  within each user comment develop a vote up vote down button to see a positive/negative response from other users on comments.  | 2       |  Vote Up / Down Button to be styled with CSS and functionality created with JavaScript   |

1. Target User Stories Estimation: 8 Story points
2. Team Velocity: 4
3. number of iterations required: 2 Iterations
