### ISSUE TITLE
USER STORY 1 - Poll - Site Admin

### ISSUE THREAD

**Issue by bdolan55** [bdolan55/My-First-Agile-Project#5]
In order to **engage users** as a **Site Admin**, I can **create a poll in the members section to see the feedback from members on a particular topic**

**Comment by bdolan55** [comment]
### Tasks
- [ ] "Views & Qs" page to show amount of votes made i total or information on how many users have engaged with poll using a button listener on the type of poll
- [ ] The ability to reply to comments below a paticular poll as the site administrator
- [ ] Create a delete comment button for the site admin to remove any rude or mean comments.
- [ ] Create a timer on the poll to get a final view on a topic in a certain amount of time
